# Generated by Django 4.2.1 on 2023-05-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='nombre',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='zapatilla',
        ),
    ]
