# Generated by Django 4.2.1 on 2023-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_contenido_comentario_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapatilla',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
